# Copyright (c) 2012-2016 Codenvy, S.A., Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

FROM eclipse/che-server:nightly

RUN rm -rf /home/user/
ADD eclipse-che.tar.gz /home/user/
